# Generated by Django 5.2.6 on 2026-08-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_adminsettings_id_alter_ecoprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
