# Generated by Django 5.2.6 on 2026-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
