# Generated by Django 6.0.7 on 2026-08-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustbins', '0002_dustbin_is_full_alter_dustbin_dustbin_type'),
        ('tasks', '0002_task_after_image_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dustbin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dustbins.dustbin'),
        ),
    ]
