# Generated by Django 6.0.7 on 2026-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_completion/'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
