# Generated by Django 6.0.7 on 2026-08-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_dustbin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_before/'),
        ),
        migrations.AddField(
            model_name='task',
            name='cleaning_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
