# Generated by Django 6.0.7 on 2026-08-05 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_points', models.IntegerField(default=0)),
                ('total_scans', models.IntegerField(default=0)),
                ('badge', models.CharField(default='Eco Beginner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
