# Generated by Django 6.0.7 on 2026-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustbins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dustbin',
            name='dustbin_type',
            field=models.CharField(choices=[('Organic', 'Organic'), ('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('E-Waste', 'E-Waste'), ('General', 'General')], max_length=50),
        ),
    ]
