# Generated by Django 5.2.6 on 2026-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustbins', '0002_dustbin_is_full_alter_dustbin_dustbin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dustbin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
