# Generated by Django 6.0.7 on 2026-08-03 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='waste_images/')),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Glass', 'Glass'), ('Metal', 'Metal'), ('Organic', 'Organic'), ('E-Waste', 'E-Waste'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
