# Generated by Django 6.0.7 on 2026-08-06 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustbin_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbinreport',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='after_cleaning/'),
        ),
        migrations.AddField(
            model_name='dustbinreport',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dustbinreport',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='before_cleaning/'),
        ),
    ]
