# Generated by Django 6.0.7 on 2026-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustbin_reports', '0002_dustbinreport_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dustbinreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Cleaning', 'Cleaning'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
