# Generated by Django 6.0.7 on 2026-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
